# translation of python-fedora.devel.python-fedora.it.po to Italiano
# Italian translations for python-fedora.
# This file is distributed under the same license as the python-fedora
# project.
#
# mario_santagiuliana <mario at marionline.it>, 2009.
msgid ""
msgstr ""
"Project-Id-Version:  python-fedora.devel.python-fedora.it\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-05-13 22:15+0700\n"
"PO-Revision-Date: 2010-03-13 00:59-0500\n"
"Last-Translator: mario_santagiuliana <mario at marionline.it>\n"
"Language-Team: Italian <fedora-trans-it at redhat.com>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: fedora/release.py:9
msgid "Python modules for interacting with Fedora Services"
msgstr "Moduli Python per interagire con i servizi di Fedora"

#: fedora/release.py:10
msgid ""
"\n"
"The Fedora Project runs many different services.  These services help us "
"to\n"
"package software, develop new programs, and generally put together the "
"distro.\n"
"This package contains software that helps us do that.\n"
msgstr ""
"\n"
"Il Fedora Project offre differenti servizi.  Questi servizi aiutano a\n"
"pacchettizzare il software, costruire nuovi programmi e metterli insieme\n"
"nella distro.\n"
"Questo pacchetto contiene il software che aiuta in questo.\n"

#: fedora/textutils.py:79
#, python-format
msgid ""
"to_unicode was given \"%(obj)s\" which is neither a byte string (str) or "
"a unicode string"
msgstr ""

#: fedora/textutils.py:82 fedora/textutils.py:140
#, python-format
msgid "non_string value, %(param)s, is not set to a valid action"
msgstr ""

#: fedora/textutils.py:137
#, python-format
msgid ""
"to_bytes was given \"%(obj)s\" which is neither a unicode string or a "
"byte string (str)"
msgstr ""

#: fedora/accounts/fas2.py:8
msgid ""
"fedora.accounts.fas2 has moved to fedora.client.fas2.  This location will"
" disappear in 0.4"
msgstr ""
"fedora.accounts.fas2 è stato spostato in fedora.client.fas2.  Questa "
"locazione scomparirà in 0.4"

#: fedora/client/baseclient.py:85 fedora/client/baseclient.py:204
#: fedora/client/baseclient.py:223 fedora/client/baseclient.py:235
msgid "session_cookie is deprecated, use session_id instead"
msgstr "session_cookie è deprecato, usare session_id invece"

#: fedora/client/baseclient.py:103
#, python-format
msgid "Unable to load session from %(file)s"
msgstr "Impossibile caricare la sessione da %(file)s"

#: fedora/client/baseclient.py:120
#, python-format
msgid "Unable to create %(dir)s: %(error)s"
msgstr "Impossibile creare %(dir)s: %(error)s"

#: fedora/client/baseclient.py:132
#, python-format
msgid "Unable to write to session file %(session)s: %(error)s"
msgstr "Impossibile scrivere sul file di sessione %(session)s: %(error)s"

#: fedora/client/baseclient.py:154
#, python-format
msgid "No session cached for \"%s\""
msgstr "Nessuna sessione memorizzata per \"%s\""

#: fedora/client/baseclient.py:276
#, python-format
msgid "send_request() got an unexpected keyword argument \"%s\""
msgstr "send_request() ha ricevuto un argomento chiave \"%s\" inaspettato"

#: fedora/client/baseclient.py:280
msgid "send_request() got an unexpected keyword argument \"input\""
msgstr "send_request() ha ricevuto un argomento chiave \"input\" inaspettato"

#: fedora/client/baseclient.py:284
msgid "send_request() got an unexpected keyword argument"
msgstr "send_request() ha ricevuto un argomento chiave inaspettato"

#: fedora/client/baseclient.py:288
msgid "send_request(input) is deprecated.  Use send_request(req_params) instead"
msgstr "send_request(input) è deprecato.  Usare send_request(req_params)"

#: fedora/client/baseclient.py:304
msgid ""
"Auth was requested but no way to perform auth was given.  Please set "
"username and password or session_id before calling this function with "
"auth=True"
msgstr ""
"E' stata richiesta l'autenticazione ma non è stato fornito nessun tipo di"
" autenticazione.  Impostare nome utente e password o session_id prima di "
"chiamare questa funzione con auth=True"

#: fedora/client/bodhi.py:191
msgid "You must specify a username"
msgstr "Bisogna specificare un nome utente"

#: fedora/client/bodhi.py:260
#, python-format
msgid "Reading from %s "
msgstr "Lettura da %s "

#: fedora/client/fas2.py:218
#, python-format
msgid "FAS server unable to retrieve group %s"
msgstr "il server FAS è incapace di recuperare il gruppo %s"

#: fedora/client/fas2.py:342
msgid "key must be one of \"id\", \"username\", or \"email\""
msgstr "la chiave deve essere o un \"id\", un \"nome utente\" o una \"email\""

#: fedora/client/fas2.py:348
#, python-format
msgid "%(field)s is not a valid field to filter"
msgstr "%(field)s non è un campo valido per ricercare"

#: fedora/client/fas2.py:397
msgid ""
"people_by_id() is deprecated and will be removed in 0.4.  Please port "
"your code to use people_by_key(key='id', fields=['human_name', 'email', "
"'username', 'bugzilla_email']) instead"
msgstr ""
"people_by_id() è deprecato e verrà rimosso in 0.4. Impostare il proprio "
"codice ad usare people_by_key(key='id', fields=['nome_reale', 'email', "
"'username', 'bugzilla_email']) al suo posto"

#: fedora/client/fas2.py:579
msgid "FAS server unable to retrieve group members"
msgstr "il server FAS è incapace di recuperare i membri del gruppo"

#: fedora/client/fas2.py:601
msgid "FAS server unable to retrieve user information"
msgstr "il server FAS è incapace di recuperare le informazioni dell'utente"

#: fedora/client/fasproxy.py:67
#, fuzzy
msgid "FasProxyClient() got an unexpected keyword argument 'session_as_cookie'"
msgstr "send_request() ha ricevuto un argomento chiave \"%s\" inaspettato"

#: fedora/client/pkgdb.py:182
#, python-format
msgid ""
"We do not have enough information to create package %(pkg)s. Need version"
" owner."
msgstr ""
"Non si hanno abbastanza informazioni per creare il pacchetto %(pkg)s. "
"Necessaria la versione del proprietario."

#: fedora/client/pkgdb.py:193
#, python-format
msgid "PackageDB returned an error creating %(pkg)s: %(msg)s"
msgstr "PackageDB ritorna un errore creando %(pkg)s: %(msg)s"

#: fedora/client/pkgdb.py:216 fedora/client/pkgdb.py:272
#, python-format
msgid "Unable to save all information for %(pkg)s: %(msg)s"
msgstr "Impossibile salvare tutte le informazioni per %(pkg)s: %(msg)s"

#: fedora/client/pkgdb.py:307
#, python-format
msgid "Collection abbreviation %(collection)s is unknown.  Use F, FC, EL, or OLPC"
msgstr ""
"L'abbreviazione di raccolta %(collection)s è sconosciuta. Usare F, FC, EL"
" o OLPC"

#: fedora/client/pkgdb.py:332
msgid ""
"collection and collection_ver are deprecated names for collctn_name and "
"collctn_ver respectively.  Ignoring the values given in them."
msgstr ""

#: fedora/client/pkgdb.py:338
msgid ""
"collection has been renamed to collctn_name.\n"
"Please start using the new name.  collection will go away in 0.4.x."
msgstr ""

#: fedora/client/pkgdb.py:344
msgid ""
"collection_ver has been renamed to collctn_ver.\n"
"Please start using the new name.  collection_ver will go away in 0.4.x."
msgstr ""

#: fedora/client/pkgdb.py:381
msgid ""
"collectn_list is a deprecated name for collctn_list.\n"
"Ignoring the value of collectn_list."
msgstr ""

#: fedora/client/pkgdb.py:386
msgid ""
"collectn_list has been renamed to collctn_list.\n"
"Please start using the new name.  collectn_list will go away in 0.4.x."
msgstr ""

#: fedora/client/pkgdb.py:460
msgid ""
"collectn is a deprecated name for collctn.\n"
"Ignoring the value of collectn."
msgstr ""

#: fedora/client/pkgdb.py:465
msgid ""
"collectn has been renamed to collctn.\n"
"Please start using the new name.  collectn will go away in 0.4.x."
msgstr ""

#: fedora/client/pkgdb.py:475
#, fuzzy, python-format
msgid "Collection shortname %(collctn)s is unknown."
msgstr ""
"L'abbreviazione di raccolta %(collctn)s è sconosciuta. Usare F, FC, EL o "
"OLPC"

#: fedora/client/proxyclient.py:149
msgid "proxyclient.__init__:entered"
msgstr "proxyclient.__init__:entered"

#: fedora/client/proxyclient.py:158
msgid ""
"Returning cookies from send_request() is deprecated and will be removed "
"in 0.4.  Please port your code to use a session_id instead by calling the"
" ProxyClient constructor with session_as_cookie=False"
msgstr ""
"Ritornare cookie da send_request() è deprecato e verrà rimosso in 0.4. "
"Correggere il proprio codice usando session_id per richiamare il "
"costrutto ProxyClient con session_as_cookie=False"

#: fedora/client/proxyclient.py:164
msgid "proxyclient.__init__:exited"
msgstr "proxyclient.__init__:exited"

#: fedora/client/proxyclient.py:236
msgid "proxyclient.send_request: entered"
msgstr "proxyclient.send_request: entered"

#: fedora/client/proxyclient.py:245
msgid ""
"Giving a cookie to send_request() to authenticate is deprecated and will "
"be removed in 0.4. Please port your code to use session_id instead."
msgstr ""
"Dare un cookie a send_request() per l'autenticazione è deprecato e verrà "
"rimosso in 0.4. Correggere il proprio codice usando session_id ."

#: fedora/client/proxyclient.py:255
msgid "username and password must both be set in auth_params"
msgstr "nome utente e password devono essere entrambi impostati in auth_params"

#: fedora/client/proxyclient.py:258
msgid ""
"No known authentication methods specified: set \"cookie\" in auth_params "
"or set both username and password in auth_params"
msgstr ""
"Nessun metodo di autenticazione specificato: impostare \"cookie\" in "
"auth_params o impostare sia nome utente e password in auth_params"

#: fedora/client/proxyclient.py:315
#, python-format
msgid "Creating request %(url)s"
msgstr "Creazione %(url)s richiesto"

#: fedora/client/proxyclient.py:316
#, python-format
msgid "Headers: %(header)s"
msgstr "Intestazione: %(header)s"

#: fedora/client/proxyclient.py:320
#, python-format
msgid "Data: %(data)s"
msgstr "Data: %(data)s"

#: fedora/client/proxyclient.py:332
msgid "Authentication failed logging in"
msgstr "Autenticazione per il login fallita"

#: fedora/client/proxyclient.py:334
msgid ""
"Unable to log into server.  Invalid authentication tokens.  Send new "
"username and password"
msgstr ""
"Impossibile entrare nel server.  Credenziali di accesso non valide.  "
"Inviarenuovi nome utente e password"

#: fedora/client/proxyclient.py:340
msgid "Unknown HTTP Server Response"
msgstr "Risposta server HTTP sconosciuta"

#: fedora/client/proxyclient.py:362
#, python-format
msgid "Error returned from simplejson while processing %(url)s: %(err)s"
msgstr "Errore da simplejson mentre processava %(url)s: %(err)s"

#: fedora/client/proxyclient.py:377
msgid "proxyclient.send_request: exited"
msgstr "proxyclient.send_request: exited"

#: fedora/client/wiki.py:64
#, python-format
msgid "Login failed: %s"
msgstr "Login fallito: %s"

#: fedora/client/wiki.py:85
#, python-format
msgid "From %(then)s to %(now)s"
msgstr "Da %(then)s a %(now)s"

#: fedora/client/wiki.py:88
#, python-format
msgid "%d wiki changes in the past week"
msgstr "%d cambiamenti wiki nella scorsa settimana"

#: fedora/client/wiki.py:90
msgid ""
"Warning: Number of changes reaches the API return limit.\n"
"You will not get the complete list of changes unless\n"
"you run this script using a 'bot' account."
msgstr ""
"Avvertenza: Numero di cambiamenti portano l'API al limite.\n"
"Non si otterrà la lista completa di cambiamenti a meno che\n"
"non si usa lo script in un account 'bot'."

#: fedora/client/wiki.py:100
msgid ""
"\n"
"== Most active wiki users =="
msgstr ""
"\n"
"== Utenti wiki più attivi =="

#: fedora/client/wiki.py:107
msgid ""
"\n"
"== Most edited pages =="
msgstr ""
"\n"
"== Pagine più modificate =="

#: fedora/compat25/defaultdict.py:40
msgid "First argument must be callable"
msgstr "Il primo argomento deve essere richiamabile"

#: fedora/django/auth/models.py:50
msgid "Loading FAS groups..."
msgstr "Caricamento gruppi FAS..."

#: fedora/django/auth/models.py:56
msgid "Unable to load FAS groups. Did you set FAS_USERNAME and FAS_PASSWORD?"
msgstr ""
"Impossibile caricare i gruppi FAS. Sono stati impostati FAS_USERNAME e "
"FAS_PASSWORD?"

#: fedora/django/auth/models.py:63
msgid "FAS groups loaded. Don't forget to unset FAS_USERNAME and FAS_PASSWORD."
msgstr ""
"Gruppi FAS caricati. Non dimenticare di togliere FAS_USERNAME e "
"FAS_PASSWORD."

#: fedora/tg/client.py:8
msgid ""
"fedora.tg.client has moved to fedora.client.  This location will "
"disappear in 0.4"
msgstr ""
"fedora.tg.client è stato spostato a fedora.client.  Questa locazione "
"scompariràin 0.4"

#: fedora/tg/controllers.py:60
#, python-format
msgid "Welcome, %s"
msgstr "Benvenuto, %s"

#: fedora/tg/controllers.py:69
msgid ""
"The credentials you supplied were not correct or did not grant access to "
"this resource."
msgstr ""
"Le credenziali fornite non sono corrette o non garantiscono l'accesso a "
"questa risorsa."

#: fedora/tg/controllers.py:72
msgid "You must provide your credentials before accessing this resource."
msgstr "Si devono fornire le proprie credenziali prima di accedere alla risorsa."

#: fedora/tg/controllers.py:75
msgid "Please log in."
msgstr "Per favore autenticarsi."

#: fedora/tg/controllers.py:100
msgid "You have successfully logged out."
msgstr "Ti sei disconnesso correttamente."

#: fedora/tg/tg1utils.py:100
msgid "url() expects a dictionary for query parameters"
msgstr "url() esige un dizionario per i parametri query"

#: fedora/tg/util.py:40
msgid ""
"fedora.tg.util is deprecated.  Switch to one of these instead:   TG1 "
"apps: fedora.tg.tg1utils   TG2 apps: fedora.tg.tg2utils.  This file will "
"disappear in 0.4"
msgstr ""

#: fedora/tg/identity/jsonfasprovider1.py:227
#: fedora/tg/identity/jsonfasprovider2.py:389
#, python-format
msgid "Error logging in %(user)s: %(error)s"
msgstr "Errore autenticazione %(user)s: %(error)s"

#: fedora/tg/identity/jsonfasprovider2.py:60
msgid ""
"Cannot enable ssl certificate auth via identity.ssl without setting "
"fas.usernamme and fas.password for authorization"
msgstr ""
"Impossibile abilitare l'autenticazione ssl via identity.ssl senza "
"impostare fas.username e fas.password per l'autorizzazione"

#: fedora/tg/identity/jsonfasprovider2.py:155
#, python-format
msgid "jsonfasprovider, ssl, returned errors from send_request: %s"
msgstr "jsonfasprovider, ssl, ritornano errori da send_request: %s"

#: fedora/tg/identity/jsonfasprovider2.py:166
#, python-format
msgid "jsonfasprovider returned errors from send_request: %s"
msgstr "jsonfasprovider ritorna errori da send_request: %s"

#: fedora/tg/templates/genshi/login.html:10
msgid "Log In"
msgstr "Log In"

#: fedora/tg/templates/genshi/login.html:14
msgid "User Name:"
msgstr "Nome utente:"

#: fedora/tg/templates/genshi/login.html:17
msgid "Password:"
msgstr "Password:"

#: fedora/tg/templates/genshi/login.html:21
#: fedora/tg/templates/genshi/login.html:84
msgid "Login"
msgstr "Entra"

#: fedora/tg/templates/genshi/login.html:28
msgid "CSRF attacks"
msgstr "attacchi CSRF"

#: fedora/tg/templates/genshi/login.html:29
msgid ""
" are a means for a malicious website to make a request of another\n"
"        web server as the user who contacted the malicious web site.  The"
"\n"
"        purpose of this page is to help protect your account and this "
"server\n"
"        from attacks from such malicious web sites.  By clicking below, "
"you are\n"
"        proving that you are a person rather than just the web browser\n"
"        forwarding your authentication cookies on behalf of a malicious\n"
"        website."
msgstr ""
" sono un tramite per siti web malevoli per fare una richiesta di un altro"
"\n"
"        il web server come un utente che contatta il sito web maligno."
"        Lo scopo di questa pagina è di aiutare a proteggere il tuo "
"account\n"
"        e questo server da attacchi da questi siti web malevoli.  "
"Cliccando\n"
"        qui sotto, sarà provato che tu sei una persona e non solo un\n"
"        browser web che inoltra i tuoi coockie di autenticazione a nome\n"
"        di un sito web malevolo."

#: fedora/tg/templates/genshi/login.html:36
msgid "I am a human"
msgstr "Sono un uomo"

#: fedora/tg/templates/genshi/login.html:41
msgid "Forgot Password?"
msgstr "Passowrd dimenticata?"

#: fedora/tg/templates/genshi/login.html:42
msgid "Sign Up"
msgstr "Iscriviti"

#: fedora/tg/templates/genshi/login.html:60
msgid "Welcome"
msgstr "Benvenuto"

#: fedora/tg/templates/genshi/login.html:82
msgid "You are not logged in"
msgstr "Non sei autenticato"

#: fedora/tg/templates/genshi/login.html:89
msgid "CSRF protected"
msgstr "CSRF protetto"

#: fedora/tg/templates/genshi/login.html:91
msgid "Verify Login"
msgstr "Verifica Login"

#: fedora/tg/templates/genshi/login.html:97
msgid "Logout"
msgstr "Uscita"

#: fedora/tg/visit/jsonfasvisit1.py:107 fedora/tg/visit/jsonfasvisit2.py:108
#, python-format
msgid "updating visit (%s)"
msgstr "aggiornamento visite (%s)"

#: fedora/wsgi/csrf.py:117
msgid "Creating CSRFProtectionMiddleware"
msgstr ""

#: fedora/wsgi/csrf.py:126
#, python-format
msgid "clean_environ(%s)"
msgstr ""

#: fedora/wsgi/csrf.py:129
#, python-format
msgid "Deleting %(key)s from environ"
msgstr ""

#: fedora/wsgi/csrf.py:141
#, python-format
msgid "CSRFProtectionMiddleware(%(r_path)s)"
msgstr ""

#: fedora/wsgi/csrf.py:148
msgid "User supplied CSRF token matches environ!"
msgstr ""

#: fedora/wsgi/csrf.py:151
msgid "Clearing identity"
msgstr ""

#: fedora/wsgi/csrf.py:154
#, python-format
msgid ""
"Invalid CSRF token.  User supplied (%(u_token)s) does not match what's in"
" our environ (%(e_token)s)"
msgstr ""

#: fedora/wsgi/csrf.py:162
msgid "CSRF_AUTH_STATE; rewriting headers"
msgstr ""

#: fedora/wsgi/csrf.py:168
#, python-format
msgid "response.location = %(r_loc)s"
msgstr ""

#: fedora/wsgi/csrf.py:240
#, python-format
msgid "CSRFMetadataProvider.add_metadata(%(r_path)s)"
msgstr ""

#: fedora/wsgi/csrf.py:246
#, python-format
msgid "session_id = %(s_id)r"
msgstr ""

#: fedora/wsgi/csrf.py:251
msgid "Identity updated with CSRF token"
msgstr ""

#: fedora/wsgi/csrf.py:254
msgid "Setting CSRF_AUTH_STATE"
msgstr ""

#: fedora/wsgi/csrf.py:264
msgid "Got HTTPFound(302) from repoze.who.application"
msgstr ""

#: fedora/wsgi/csrf.py:270
#, fuzzy, python-format
msgid "Altered headers: %(headers)s"
msgstr "Intestazione: %(headers)s"

#: fedora/wsgi/csrf.py:273
#, python-format
msgid "Invalid session cookie %(s_id)r, not setting CSRF token!"
msgstr ""

#: fedora/wsgi/csrf.py:283
#, python-format
msgid "%(token)s in GET"
msgstr ""

#: fedora/wsgi/csrf.py:290
#, python-format
msgid "%(token)s in POST"
msgstr ""

#: fedora/wsgi/faswho/faswhoplugin.py:110
msgid "Keep alive cache miss"
msgstr ""

#: fedora/wsgi/faswho/faswhoplugin.py:124
msgid "in identify()"
msgstr ""

#: fedora/wsgi/faswho/faswhoplugin.py:131
#, python-format
msgid "Request identify for cookie %(cookie)s"
msgstr ""

#: fedora/wsgi/faswho/faswhoplugin.py:155
msgid "In remember()"
msgstr ""

#: fedora/wsgi/faswho/faswhoplugin.py:168
msgid "In forget()"
msgstr ""

#: fedora/wsgi/faswho/faswhoplugin.py:175
#, python-format
msgid "Forgetting login data for cookie %(s_id)s"
msgstr ""

#: fedora/wsgi/faswho/faswhoplugin.py:192
msgid "In authenticate()"
msgstr ""

#: fedora/wsgi/faswho/faswhoplugin.py:216
#, fuzzy
msgid "Authentication failed, setting error"
msgstr "Autenticazione per il login fallita"

#: fedora/wsgi/faswho/faswhoplugin.py:237
msgid "An unknown error happened when trying to log you in.  Please try again."
msgstr ""

#: fedora/wsgi/faswho/faswhoplugin.py:248
msgid "Metadata cache miss - refreshing metadata"
msgstr ""

#: fedora/wsgi/faswho/faswhoplugin.py:279
msgid "In add_metadata"
msgstr ""

#: fedora/wsgi/faswho/faswhoplugin.py:283
msgid "Error exists in session, no need to set metadata"
msgstr ""

#: fedora/wsgi/faswho/faswhoplugin.py:293
#, python-format
msgid "Request metadata for cookie %(cookie)s"
msgstr ""

#: fedora/wsgi/test/controllers/root.py:31
msgid "Wrong credentials"
msgstr ""

#: fedora/wsgi/test/controllers/root.py:46
#, fuzzy, python-format
msgid "Welcome back, %s!"
msgstr "Benvenuto, %s"

#: fedora/wsgi/test/controllers/root.py:56
msgid "We hope to see you soon!"
msgstr ""

